# -*- coding: utf-8 -*-
"""Lab 1 (A* Search)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NFQ_QYXXNx3dEblIbGvCKtmwLKn6jbPx

**PART 1**
"""

import heapq

# Directions: Up, Down, Left, Right
DIRS = [(-1, 0, 'U'), (1, 0, 'D'), (0, -1, 'L'), (0, 1, 'R')]

def manhattan(x1, y1, x2, y2):
    return abs(x1 - x2) + abs(y1 - y2)

def a_star(maze, start, goal, n, m):
    pq = []
    heapq.heappush(pq, (0, start))

    g_cost = {start: 0}
    parent = {}

    while pq:
        _, (x, y) = heapq.heappop(pq)

        if (x, y) == goal:
            path = []
            while (x, y) != start:
                px, py = parent[(x, y)]
                for dx, dy, move in DIRS:
                    if px + dx == x and py + dy == y:
                        path.append(move)
                x, y = px, py
            return g_cost[goal], ''.join(path[::-1])

        for dx, dy, move in DIRS:
            nx, ny = x + dx, y + dy

            if 0 <= nx < n and 0 <= ny < m and maze[nx][ny] == '0':
                new_cost = g_cost[(x, y)] + 1

                if (nx, ny) not in g_cost or new_cost < g_cost[(nx, ny)]:
                    g_cost[(nx, ny)] = new_cost
                    f = new_cost + manhattan(nx, ny, goal[0], goal[1])
                    heapq.heappush(pq, (f, (nx, ny)))
                    parent[(nx, ny)] = (x, y)

    return -1, ""

# INPUT
n, m = map(int, input().split())
sx, sy = map(int, input().split())
gx, gy = map(int, input().split())

maze = [list(input().strip()) for _ in range(n)]

cost, path = a_star(maze, (sx, sy), (gx, gy), n, m)

print(cost)
if cost != -1:
    print(path)

"""**PART 2**"""

from collections import deque

def bfs(goal, adj, n):
    d = {i: float('inf') for i in range(1,n+1)}
    d[goal] = 0
    q = deque([goal])

    while q:
        u = q.popleft()
        for v in adj[u]:
            if d[v] == float('inf'):
                d[v] = d[u] + 1
                q.append(v)
    return d

# input
n,m = map(int,input().split())
s,g = map(int,input().split())

h = {}
for _ in range(n):
    a,b = map(int,input().split())
    h[a] = b

adj = {i:[] for i in range(1,n+1)}
for _ in range(m):
    u,v = map(int,input().split())
    adj[u].append(v)
    adj[v].append(u)

d = bfs(g, adj, n)

bad = [i for i in range(1,n+1) if h[i] > d[i]]

if not bad:
    print(1)
else:
    print(0)
    print(*bad)